-- SQLite
-- Criando a tabela Customers (Clientes)

CREATE TABLE CUSTOMERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(100) NOT NULL,
    LASTNAME TEXT NOT NULL,
    PHONE VARCHAR(7) NOT NULL,
    EMAIL VARCHAR(100),
    ADDRESS TEXT NOT NULL,
    CITY TEXT NOT NULL,
    STATE VARCHAR(2) NOT NULL, 
    BIRTH_DATE DATE NOT NULL
);