-- SQLite
-- Exibindo todos os funcionários(EMPLOYEES) e seus cargos(POSITION_ID)

SELECT EMPLOYEES.ID AS 'Código',
       EMPLOYEES.NAME AS 'Funcionários',
       POSITIONS.DESCRIPTION AS 'Cargo' FROM EMPLOYEES
    JOIN POSITIONS ON (EMPLOYEES.POSITION_ID = POSITIONS.ID);